# Generated by Django 3.0 on 2019-12-24 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('company_name', models.CharField(default=' ', max_length=130)),
                ('contact', models.CharField(default=' ', max_length=30)),
                ('phone_number', models.CharField(default=' ', max_length=20)),
                ('account_type', models.CharField(choices=[('CH', 'China'), ('GL', 'Global')], default='CH', max_length=2)),
                ('account_id', models.CharField(max_length=30)),
                ('address', models.TextField(default=' ')),
                ('company_url', models.URLField(blank=True)),
                ('postal_code', models.CharField(default=' ', max_length=10)),
                ('business_plan', models.URLField(default=' ')),
                ('license', models.URLField(default=' ')),
                ('agreement', models.URLField(default=' ')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
